[package]
name = "update_uuids"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git2 = "0.19.0"
serde = { version = "1.0.214", features = ["derive"] }
serde_yaml = "0.9.34"
walkdir = "2.5.0"
